name: ProtectionsExtended
main: com.charredgames.protectionsextended.PE
version: 0.1.0
description: Enhances grief-protection plugins by disabling the use of specific tools in protected regions. Also fixes many bugs, dupes, and other annoyances.
author: Joe Boyle
website: http://www.charredgames.com